#for MacOS
os: osx
language: python
python:
  - "3.6"
# command to install dependencies
before_install: cd python-package/
install:
  - pip install codecov
  - pip install --upgrade setuptools wheel  
  - pip install --only-binary all -r requirements.txt
  - python3 setup.py install
# command to run tests 
before_script: 
  - cd ../
  - pip install tox
script:
  - tox 
  - coverage run --source learn2clean -m pytest
after_success:
  - codecov