#for MacOS
language: python
python:
  - "3.6"
# command to install dependencies
before_install: cd python-package/
install:
  - pip install codecov
  - pip install --upgrade setuptools wheel  
  - pip install --only-binary all -r requirements.txt
  - python3 setup.py install
# command to run tests
before_script: 
  - pwd
script:
  - cd ../ && make test-all
  - cp ../.coveragerc .
  - cd ../ && make coverage
  #- if [[ "$RUN_COVERAGE" == 1 ]]; then cd ../ && codecov; fi
after_success:
  - codecov