language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install codecov
  - pip install --upgrade setuptools wheel  
  - pip install --only-binary all -r python-package/requirements.txt
# command to run tests
script:
  - python ./python-package/setup.py install
  - coverage run ./python-package/tests/test_learn2clean.py
#
after_success:
- codecov